
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -3;
const int acc_off_y = 0;
const int acc_off_z = -3;
const float acc_scale_x = 253.072357;
const float acc_scale_y = 260.524777;
const float acc_scale_z = 257.383655;

const int magn_off_x = 187;
const int magn_off_y = -657;
const int magn_off_z = -57;
const float magn_scale_x = 489.500039;
const float magn_scale_y = 468.348393;
const float magn_scale_z = 495.106020;
